version: '2.0'

volumes:
    prometheus_data: {}

networks:
    node-prom:
services:
  prometheus:
    image: prom/prometheus:v2.9.2
    container_name: prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus:/etc/prometheus/
    - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'   
    depends_on:
    - cadvisor
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
    networks:
      - node-prom
    restart: always


  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    ports:
    - 8080:8080

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    depends_on:
    - node-prom
    networks:
      - node-prom


  node-prom:
    image: utsavanand2/node-prom:v0.0.1
    container_name: node-prom
    networks:
      - node-prom
    ports:
    - 8000:8000